services:
    postgres:
        build:
            context: ./postgres
        environment:
            POSTGRES_PASSWORD: sonar
            POSTGRES_USER: sonar
        networks:
            - sonarnet
        ports:
            - 5432:5432
        restart: "no"
        volumes:
            - ./postgres/postgresql/:/var/lib/postgresql
            - ./postgres/data/:/var/lib/postgresql/data
    sonarqube:
        build:
            context: ./sonarqube
        environment:
           - SONARQUBE_JDBC_URL:jdbc:postgresql://postgres:5432/sonar
        volumes:
            - ./sonar/data/:/opt/sonarqube/data
            - ./sonar/log/:/opt/sonarqube/log
            - ./sonar/extensions/:/opt/sonarqube/extensions
            - ./sonar/conf/:/opt/sonarqube/conf
        networks:
            - sonarnet
        ports:
            - 9000:9000
        restart: "no"
networks:
    sonarnet:
        driver: bridge
version: '2.0'