services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
    ports:
    - 5432:5432/tcp
    restart: always
    volumes:
    - /data/postgres:/var/lib/postgresql/data:rw
  sonarqube:
    build:
      context: ./sonarqube
    environment:
      SONARQUBE_JDBC_URL:jdbc:postgresql://db:5432/sonar: null
    links:
    - postgres
    ports:
    - 9000:9000/tcp
    restart: always
version: '2.0'