FROM sonarqube:7.4-community
## 汉化语言包
#ADD sonar-l10n-zh-plugin-1.16.jar /opt/sonarqube/extensions/plugins/

## clover 4.1
ADD ./plugins/7.4/sonar-clover-plugin-4.1.jar /opt/sonarqube/extensions/plugins/

# findbugs 3.9.4
ADD ./plugins/7.4/sonar-findbugs-plugin-3.9.4.jar /opt/sonarqube/extensions/plugins/

# sonarHTML 3.2.0
ADD ./plugins/7.4/sonar-html-plugin-3.2.0.2082.jar /opt/sonarqube/extensions/plugins/

# sonar-groovy 1.6
ADD ./plugins/7.4/sonar-groovy-plugin-1.6.jar /opt/sonarqube/extensions/plugins/

# sonar-flex 2.4
ADD ./plugins/7.4/sonar-flex-plugin-2.4.0.1222.jar /opt/sonarqube/extensions/plugins/

# sonar-mybatis 1.0.5
ADD ./plugins/7.4/sonar-mybatis-plugin-1.0.5.jar /opt/sonarqube/extensions/plugins/