FROM sonarqube:7.4-community
ADD sonar-l10n-zh-plugin-1.16.jar /opt/sonarqube/extensions/plugins/
#ADD ./plugins/7.4/sonar-clover-plugin-4.1.jar /opt/sonarqube/extensions/plugins/
# open clover
ADD clover-maven-plugin-4.4.1.jar /opt/sonarqube/extensions/plugins/